name: Copy Files Between Repositories

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜触发
  workflow_dispatch: # 允许手动触发

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the source repository (awbk)
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: iawooo/awbk
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # 2. Commit and push files to target repository (vlty)
      - name: Push to target repository
        env:
          TARGET_REPO: iawooo/vlty
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone the target repository
          git clone https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/${TARGET_REPO}.git target-repo

          # Copy all files from source to target
          cp -r ./* target-repo/

          # Change to target repository directory
          cd target-repo

          # Add, commit, and push changes
          git add .
          git commit -m "Automated file copy from awbk to vlty"
          git push origin main

    permissions:
      contents: write

# Secrets needed in your GitHub repository settings:
# 1. PERSONAL_ACCESS_TOKEN: A GitHub personal access token with repo scope
