name: Copy Files Between Repositories

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜触发
  workflow_dispatch: # 允许手动触发

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # 1. 设置 Git 用户信息
      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 2. Checkout the source repository (awbk)
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: iawooo/awbk
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: source-repo # 克隆到 source-repo 目录

      # 3. Clone the target repository (vlty)
      - name: Clone target repository
        env:
          TARGET_REPO: iawooo/vlty
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/${TARGET_REPO}.git target-repo

      # 4. Copy files from source to target
      - name: Copy files to target repository
        run: |
          cp -r source-repo/* target-repo/ # 从 source-repo 复制到 target-repo

      # 5. Commit and push changes to target repository
      - name: Commit and push to target repository
        working-directory: target-repo
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git add .
          git commit -m "Automated file copy from awbk to vlty" || echo "No changes to commit"
          git push https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/iawooo/vlty.git main

    permissions:
      contents: write

# Secrets needed in your GitHub repository settings:
# 1. PERSONAL_ACCESS_TOKEN: A GitHub personal access token with repo scope
